// Original interactive learning activities. Progress lasts for this browser session.
(() => {
 const $=s=>document.querySelector(s), pick=a=>a[Math.floor(Math.random()*a.length)], rand=(a,b)=>a+Math.floor(Math.random()*(b-a+1));
 const mix=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=rand(0,i);[a[i],a[j]]=[a[j],a[i]]}return a};
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const dateKey=()=>new Date().toLocaleDateString('en-CA');
 const skills=[
 ['phonics','Sound explorers','Explore sounds and blend words','Aa','Listen to each sound, then say them smoothly together. For cat: /k/ /a/ /t/ becomes cat.'],
 ['levels','Reading steps','Four steps from short to long vowels','▤','Read slowly. Tap a word for help. Read again and think about what happened.'],
 ['sentence','Sentence builder','Put the words in order','▦','Start with the capital letter. Put the words in an order that makes sense. Finish with the full stop.'],
 ['bonds','Number bonds','Parts that make a whole','⊕','A whole can be split into two parts. To make 10, 6 and 4 belong together.'],
 ['thinking','Brain puzzles','Sort, spot patterns and reason','◇','Look carefully. Find what is the same, what is different, or what repeats.'],
 ['skip','Number hops','Count in 2s, 5s and 10s','↗','Make equal jumps. Counting in 5s goes 5, 10, 15, 20. Each jump adds 5.'],
 ['position','Where is teddy?','Above, below, beside and between','↔','Position words tell us where something is. Above means higher; below means lower.'],
 ['measure','Measure and compare','Length, weight and capacity','↔','Compare from the same starting point. Longer takes more space. A lower balance pan holds the heavier object.'],
 ['clock','Time and calendar','Hours, quarters, days and months','◷','The short clock hand shows the hour. When the long hand points to 12, it is an exact hour.'],
 ['money','Little Aussie shop','Coins and pretend purchases','$','Read the value on each coin. Add values to find the total. A bigger coin is not always worth more.'],
 ['fractions','Fair shares','Equal groups, halves and quarters','◐','Fair shares are equal. A half is one of two equal parts. A quarter is one of four equal parts.'],
 ['graphs','Picture graphs','Read and compare picture bars','▥','Each block stands for one vote. Count the blocks to compare the groups.'],
 ['symmetry','Mirror studio','Draw both sides of a picture','⋈','The mirror line divides two matching sides. Each mark appears the same distance from the line.'],
 ['problems','Story maths','Act out a little number story','?','Listen to what changes. More arrive: add. Some leave: take away. Shared equally: split into equal groups.'],
 ['strategies','Clever adding','Doubles, count on and make five','+','Try a helpful strategy. Double 3 is 3 plus 3. To count on, keep the first number in your head and count the extra ones.'],
 ['solids','Shape detectives','Explore solid 3D shapes','▧','Solid shapes take up space. A cube has six square faces. A sphere is round like a ball. A cylinder has two circular ends.'],
 ['sight','Word treasures','Listen and find familiar words','abc','Look carefully at the whole word. Listen to it, find it, then try using it in your own sentence.'],
 ['author','My little journal','Retell a book or write a letter','✎','Tell what happened first, next and last. In a letter, say who it is for, share your idea, and sign your name.']
 ];
 function validatedProgress(p){
  if(!p||p.version!==1||!p.skills||!p.daily||!Number.isSafeInteger(p.stars)||p.stars<0)throw Error('Invalid backup');
 const clean={version:1,stars:p.stars,skills:{},daily:{},level:[0,1,2,3].includes(p.level)?p.level:0,large:p.large===true};
  for(const id of [...skills.map(s=>s[0]),'Original maths','Word play','Writing','Story reading'])if(p.skills[id]){const s=p.skills[id];if(!['tries','correct','completed'].every(k=>Number.isSafeInteger(s[k])&&s[k]>=0)||s.correct>s.tries)throw Error('Invalid skill');clean.skills[id]={tries:s.tries,correct:s.correct,completed:s.completed}}
  for(const [date,d] of Object.entries(p.daily)){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!d||!Array.isArray(d.queue)||d.queue.length!==5||!d.queue.every(id=>skills.some(s=>s[0]===id)&&!['symmetry','author'].includes(id))||!Number.isInteger(d.step)||d.step<0||d.step>5)throw Error('Invalid adventure');clean.daily[date]={queue:d.queue,step:d.step}}
  return clean;
 }
 let saved={version:1,stars:0,skills:{},daily:{},level:0,large:false};
 try{const p=JSON.parse(sessionStorage.getItem('spark-learning-v1'));if(p)saved=validatedProgress(p)}catch{}
 const persist=()=>{try{sessionStorage.setItem('spark-learning-v1',JSON.stringify(saved));return true}catch{return false}};
 const oldStar=star;stars=Number(saved.stars)||0;$('#stars').textContent=stars+' happy star'+(stars===1?'':'s');star=function(){oldStar();saved.stars=stars;persist()};
 const oldAward=award;award=function(key){const had=earned.has(key);oldAward(key);if(!had){const id=key.startsWith('math')?'Original maths':key.startsWith('word')?'Word play':key.startsWith('freewrite')?'Writing':'Story reading';const s=saved.skills[id]||(saved.skills[id]={tries:0,correct:0,completed:0});s.completed++;persist()}};
 let current=null,answeredNow=false,dailyMode=false,lastBySkill={},retry=false,timer=null,reviewRun=null;
 const nav=document.querySelector('nav[aria-label="Activities"]');const b=document.createElement('button');b.className='activity adventure-nav';b.dataset.mode='adventure';b.innerHTML='<span class="tile-icon">✦</span><span><b>Let’s explore</b><small>New skills & daily adventures</small></span>';b.onclick=()=>{dailyMode=false;switchMode('adventure')};nav.append(b);
 const originalRender=render;render=function(){stopVoice();clearTimeout(timer);if(mode==='adventure'){cancelAdvance();stopTracing();if(observer)observer.disconnect();home();return}originalRender()};
 const options=(answer,others)=>mix([...new Set([answer,...others])]).slice(0,4);
 function nums(n,max=1000){const s=new Set([n]);for(let d=1;s.size<4;d++){if(n-d>=0)s.add(n-d);if(s.size<4&&n+d<=max)s.add(n+d)}return mix([...s])}
 const meta=id=>skills.find(s=>s[0]===id);
 const blocks=(n,colour='#8061d5')=>`<div class="learning-blocks" aria-label="${n} objects">${Array.from({length:n},()=>`<span style="background:${colour}"></span>`).join('')}</div>`;
 const svg=(body,label)=>`<svg class="learning-svg" viewBox="0 0 420 210" role="img" aria-label="${esc(label)}">${body}</svg>`;
 const teddy=(x,y)=>`<g transform="translate(${x} ${y})"><circle cx="-17" cy="-20" r="11" fill="#bc8758"/><circle cx="17" cy="-20" r="11" fill="#bc8758"/><circle r="26" fill="#dca776"/><ellipse cy="9" rx="13" ry="10" fill="#f7dbad"/><circle cx="-9" cy="-4" r="2.7"/><circle cx="9" cy="-4" r="2.7"/><ellipse cy="6" rx="4" ry="3"/></g>`;
 function header(title){return `<div class="explore-top"><button class="button" id="exploreHome">← All adventures</button><span class="pill">${dailyMode?'TODAY’S ADVENTURE':'PLAY · PRACTISE · GROW'}</span></div><h2>${title}</h2>`}
 function bindHome(){$('#exploreHome').onclick=()=>{cancelAdvance();stopVoice();dailyMode=false;reviewRun=null;home();scrollActivity()}}
 function today(){const key=dateKey();if(!saved.daily[key]){const days=Object.values(saved.daily).filter(d=>d.step===5).length;const sequence=[['phonics','levels','sentence','bonds','thinking'],['sight','levels','strategies','skip','position'],['phonics','sentence','measure','solids','fractions'],['sight','levels','money','clock','graphs'],['phonics','sentence','problems','thinking','bonds']];saved.daily[key]={queue:sequence[days%sequence.length],step:0};persist()}return saved.daily[key]}
 function home(){current=null;reviewRun=null;cancelAdvance();stopVoice();const day=today(),done=day.step>=day.queue.length;
 $('#workspace').innerHTML=`<div class="explore-shell"><div class="daily-banner"><div><span class="mini-label">A LITTLE LEARNING, EVERY DAY</span><h2>Today’s adventure</h2><p>Five little activities. Take breaks whenever you like.</p><p>${day.step} of ${day.queue.length} complete</p></div><button class="button primary" id="dailyStart">${done?'Adventure complete!':day.step?'Continue adventure':'Let’s begin →'}</button></div><div class="explore-actions"><button class="button" id="parentProgress">This session’s progress</button><button class="button" id="printPractice">Printable practice</button></div><div class="adventure-grid">${skills.map(([id,title,desc,icon])=>`<button class="adventure-card" data-skill="${id}"><span class="adventure-icon">${icon}</span><strong>${title}</strong><span>${desc}</span><small>${saved.skills[id]?.completed||0} activities completed</small></button>`).join('')}</div></div>`;
 organiseActivities();document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{dailyMode=false;start(b.dataset.skill)});$('#dailyStart').disabled=done;$('#dailyStart').onclick=()=>{dailyMode=true;start(day.queue[day.step])};$('#parentProgress').onclick=progress;$('#printPractice').onclick=printMenu;const review=document.createElement('button');review.className='button';review.textContent='Five-skill check-in';review.onclick=()=>{dailyMode=false;reviewRun={queue:['phonics','bonds',pick(['measure','clock','money']),pick(['thinking','position','solids']),'levels'],step:0,first:0};start(reviewRun.queue[0])};$('.explore-actions').append(review);}
 function organiseActivities(){const groups=[['words','Words & stories',['phonics','levels','sight','sentence','author']],['numbers','Number adventures',['bonds','strategies','skip','money','fractions','graphs','problems']],['discover','Explore & think',['thinking','position','measure','clock','solids']],['create','Create',['symmetry']]],grid=$('.adventure-grid'),filter=document.createElement('div');filter.className='explore-filter';filter.setAttribute('aria-label','Choose an adventure subject');filter.innerHTML=[['all','All adventures'],...groups.map(([id,name])=>[id,name])].map(([id,name])=>`<button class="button ${id==='all'?'primary':''}" data-category="${id}" aria-pressed="${id==='all'}">${name}</button>`).join('');grid.before(filter);for(const [id,name,ids] of groups){const h=document.createElement('h3');h.className='adventure-group-title';h.dataset.group=id;h.textContent=name;grid.append(h);for(const skill of ids){const card=grid.querySelector(`[data-skill="${skill}"]`);card.dataset.group=id;grid.append(card)}}filter.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{filter.querySelectorAll('button').forEach(other=>{other.classList.toggle('primary',other===b);other.setAttribute('aria-pressed',other===b)});grid.querySelectorAll('[data-group]').forEach(node=>node.hidden=b.dataset.category!=='all'&&node.dataset.group!==b.dataset.category)})}
 function skillLevel(id){const s=saved.skills[id];return s&&s.completed>=8&&s.correct/Math.max(1,s.tries)>=.75?1:0}
 const phonics=[['cat',['c','a','t'],['cat','dog','sun'],'a'],['dog',['d','o','g'],['dog','cat','hen'],'o'],['sun',['s','u','n'],['sun','hat','bed'],'u'],['hen',['h','e','n'],['hen','pig','cat'],'e'],['pig',['p','i','g'],['pig','sun','dog'],'i'],['hat',['h','a','t'],['hat','bed','fish'],'a'],['fish',['f','i','sh'],['fish','cat','hen'],'i'],['ship',['sh','i','p'],['ship','hat','sun'],'i'],['chop',['ch','o','p'],['chop','cat','bed'],'o']];
 const readers=[
 [{text:'Sam has a cat. The cat is on a mat. Sam can pat the cat.',ask:'Where is the cat?',answer:'On a mat',choices:['On a mat','In a bus','In a bed'],clue:'cat'},{text:'A dog can run. The dog has a red ball. The dog is hot.',ask:'What does the dog have?',answer:'A red ball',choices:['A red ball','A hat','A book'],clue:'dog'},{text:'A hen is in a pen. The hen has an egg. Ben can see the egg.',ask:'What can Ben see?',answer:'An egg',choices:['An egg','A cat','A cup'],clue:'hen'}],
 [{text:'A fish is in a dish. The dish is big. Josh can see the fish.',ask:'What is in the dish?',answer:'A fish',choices:['A fish','A cat','A hat'],clue:'fish'},{text:'Chip has a hat. Chip can chop a log. The hat is on Chip.',ask:'What can Chip chop?',answer:'A log',choices:['A log','A fish','A dish'],clue:'hat'},{text:'Shan has a shell. The shell is in a bag. Shan lifts the bag.',ask:'Where is the shell?',answer:'In a bag',choices:['In a bag','On a bed','In a cup'],clue:'shell'}],
 [{text:'A bee is on a tree. Lee can see the bee. The bee can fly.',ask:'What can Lee see?',answer:'A bee',choices:['A bee','A dog','A goat'],clue:'tree'},{text:'A goat is on a boat. The boat is on a lake. The goat has a coat.',ask:'Where is the goat?',answer:'On a boat',choices:['On a boat','In a tree','On a bed'],clue:'boat'},{text:'A sheep can sleep. It is next to a tree. The sheep has a deep sleep.',ask:'What does the sheep do?',answer:'Sleeps',choices:['Sleeps','Swims','Runs'],clue:'tree'}]
 ];
 readers.push([{text:'Jay can play in the rain. Jay has a coat. The rain stops and Jay runs home.',ask:'What does Jay have?',answer:'A coat',choices:['A coat','A boat','A cake'],clue:'coat'},{text:'A boy has a toy boat. He puts it in a pool. The boy can see the boat float.',ask:'What toy does the boy have?',answer:'A boat',choices:['A boat','A car','A kite'],clue:'boat'},{text:'A mouse is in a house. It runs out to find food. The mouse finds a seed.',ask:'What does the mouse find?',answer:'A seed',choices:['A seed','A coat','A toy'],clue:'house'}]);
 const dayNames=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
 function make(id){const hard=skillLevel(id);let q={id};
 if(id==='phonics'){const p=pick(phonics.slice(0,hard?9:6));const soundRound=Math.random()<.5;q={...q,prompt:soundRound?'Which word has this middle sound?':'Blend the sounds. Which word do they make?',answer:p[0],choices:mix(p[2]),html:`<div class="sound-tiles">${(soundRound?[p[3]]:p[1]).map(s=>`<span>${s}</span>`).join('')}</div><p>${soundRound?'Say the vowel sound, then try each word.':'Point to each sound. Say it, then blend.'}</p>`,speech:soundRound?`Find the word with the vowel sound in ${p[0]}.`:`Listen to the whole word: ${p[0]}.`,help:`${p[0]} has the sounds ${p[1].join(' · ')}. Say them smoothly together.`,blend:p[0]};}
 if(id==='levels'){const p=pick(readers[saved.level||0]);q={...q,prompt:p.ask,answer:p.answer,choices:mix(p.choices),html:pictureClue(p.clue)+`<div class="level-passage">${wordButtons(p.text)}</div>`,help:`Read this again: ${p.text}`,speech:p.text+' '+p.ask};}
 if(id==='sentence'){const s=pick(['The cat is on the mat.','I can see a red bus.','The dog has a ball.','We can read a book.','The fish can swim.','I put on my hat.','The sun is up.','A bird is in the tree.']);q={...q,prompt:'Build this sentence.',sentence:s,html:pictureClue(s),help:'Start with '+s.split(' ')[0]+'. Listen to the sentence, then put the words in order.',speech:s};}
 if(id==='bonds'){const total=hard?pick([10,12,15,20]):pick([5,6,8,10]),part=rand(1,total-1);q={...q,prompt:`${part} and how many more make ${total}?`,answer:total-part,choices:nums(total-part,20),html:`<div class="bond-model"><b>${total}</b><div><span>${part}</span><span>?</span></div></div>${blocks(part)}`,help:`Start at ${part} and count on to ${total}. You need ${total-part} more.`};}
 if(id==='skip'){const step=pick([2,5,10]),max=saved.large?1000:hard?100:40,start=rand(0,Math.floor(max/step)-4)*step,seq=[start,start+step,start+2*step];q={...q,prompt:`Hop in ${step}s. What comes next?`,answer:start+3*step,choices:nums(start+3*step,1000),html:`<div class="number-hops">${seq.map(n=>`<span>${n}</span><b>+${step} →</b>`).join('')}<span>?</span></div>`,help:`Add ${step} to ${seq[2]}. ${seq[2]} plus ${step} is ${start+3*step}.`};}
 if(id==='thinking'){const type=rand(0,4);if(type===0){const shapes=['●','▲','■'],a=pick(shapes),b=pick(shapes.filter(s=>s!==a));q={...q,prompt:'What comes next?',answer:b,choices:mix(shapes),html:`<div class="puzzle-line">${[a,a,b,a,a,'?'].join(' ')}</div>`,help:`The repeating group is ${a} ${a} ${b}. So ${b} comes next.`}}
 else if(type===1){const group=pick([['Fruit','apple','pear','banana','bus'],['Animals','cat','dog','hen','hat'],['Things to wear','hat','coat','boot','fish']]);q={...q,prompt:'Which one does not belong?',answer:group[4],choices:mix(group.slice(1)),html:`<div class="clue-row">${group.slice(1).map(pictureClue).join('')}</div>`,help:`The others are ${group[0].toLowerCase()}. ${group[4]} belongs in a different group.`}}
 else if(type===2){const item=pick([['apple','Fruit'],['dog','Animals'],['hat','Clothes'],['pear','Fruit'],['cat','Animals'],['boot','Clothes']]);q={...q,prompt:'Which basket does this belong in?',answer:item[1],choices:['Fruit','Animals','Clothes'],html:pictureClue(item[0]),help:`A ${item[0]} belongs in the ${item[1].toLowerCase()} basket.`}}
 else if(type===3){q={...q,prompt:'Which tower is taller than A but shorter than C?',answer:'B',choices:mix(['A','B','C']),html:`<div class="tower-row">${[['A',2],['B',4],['C',6]].map(([l,n])=>`<div>${blocks(n)}<strong>${l}</strong></div>`).join('')}</div>`,help:'A has 2 blocks, B has 4, and C has 6. B is between the other two in height.'}}else{const step=pick([1,2,5]),up=Math.random()<.5,start=up?rand(0,5):step*4+rand(0,5),seq=Array.from({length:3},(_,i)=>start+(up?1:-1)*step*i),ans=start+(up?1:-1)*step*3;q={...q,prompt:'This pattern is '+(up?'growing':'shrinking')+'. What comes next?',answer:ans,choices:nums(ans,50),html:'<div class="puzzle-line">'+seq.join(' · ')+' · ?</div>',help:'The numbers '+(up?'grow':'shrink')+' by '+step+' each time. The next number is '+ans+'.'}}}
 if(id==='position'){const p=pick(['above','below','beside','between']);let scene='<rect x="165" y="85" width="90" height="60" rx="8" fill="#8a70d3"/>';if(p==='above')scene+=teddy(210,40);if(p==='below')scene+=teddy(210,181);if(p==='beside')scene+=teddy(305,115);if(p==='between')scene='<rect x="85" y="85" width="65" height="60" rx="8" fill="#8a70d3"/><rect x="270" y="85" width="65" height="60" rx="8" fill="#8a70d3"/>'+teddy(210,115);q={...q,prompt:p==='between'?'Where is teddy compared with the boxes?':'Where is teddy compared with the box?',answer:p,choices:mix(['above','below','beside','between']),html:svg(scene,'Teddy and boxes'),help:`Teddy is ${p} the ${p==='between'?'boxes':'box'}.`};}
 if(id==='measure'){const type=rand(0,2),left=rand(2,5),right=left+rand(1,3),swap=Math.random()<.5,a=swap?right:left,b=swap?left:right;let body,prompt,answer;
 if(type===0){prompt='Which ribbon is longer?';answer=a>b?'A':'B';body=`<text x="30" y="60">A</text><rect x="60" y="35" width="${a*35}" height="30" rx="8" fill="#e2769d"/><text x="30" y="140">B</text><rect x="60" y="115" width="${b*35}" height="30" rx="8" fill="#6ea7cf"/><path d="M60 20V165" stroke="#40364e" stroke-dasharray="4 4"/>`}
 else if(type===1){prompt='Which jug holds more water?';answer=a>b?'A':'B';body=[a,b].map((n,i)=>`<g transform="translate(${95+i*180} 30)"><rect x="0" y="0" width="80" height="140" rx="8" fill="#eef6ff" stroke="#587997" stroke-width="3"/><rect x="3" y="${138-n*15}" width="74" height="${n*15}" fill="#75bee1"/><text x="35" y="168">${i?'B':'A'}</text></g>`).join('')}
 else{prompt='Which object is heavier?';answer=a>b?'A':'B';const ya=a>b?120:70,yb=b>a?120:70;body=`<path d="M210 65V170M175 180H245M90 ${ya}L330 ${yb}" stroke="#665783" stroke-width="7"/><circle cx="90" cy="${ya-25}" r="23" fill="#e2769d"/><circle cx="330" cy="${yb-25}" r="23" fill="#6ea7cf"/><text x="84" y="${ya-19}">A</text><text x="324" y="${yb-19}">B</text>`}
 q={...q,prompt,answer,choices:['A','B'],html:svg(body,'Compare objects A and B'),help:type===0?`${answer} reaches farther from the same start line.`:type===1?`${answer} has a higher water level in the same-size jug.`:`${answer} is on the lower side of the balance. The heavier side goes down.`};}
 if(id==='clock'){
 const type=rand(0,3);
 if(type<2){const h=rand(1,12),m=pick([0,15,30,45]),angle=(h*30+m*.5)*Math.PI/180,ma=m*Math.PI/30,answer=`${h}:${String(m).padStart(2,'0')}`;
 q={...q,prompt:'What time is it?',answer,choices:options(answer,[`${h}:${String((m+15)%60).padStart(2,'0')}`,`${h%12+1}:${String(m).padStart(2,'0')}`,`${(h+10)%12+1}:${String(m).padStart(2,'0')}`]),html:svg(`<circle cx="210" cy="105" r="96" fill="#fff8e6" stroke="#8663cf" stroke-width="5"/>${Array.from({length:12},(_,i)=>{const n=i+1,a=n*Math.PI/6;return `<text x="${210+78*Math.sin(a)}" y="${111-78*Math.cos(a)}" text-anchor="middle" font-size="16">${n}</text>`}).join('')}<path d="M210 105L${210+65*Math.sin(ma)} ${105-65*Math.cos(ma)}" stroke="#64a4c4" stroke-width="5"/><path d="M210 105L${210+48*Math.sin(angle)} ${105-48*Math.cos(angle)}" stroke="#553388" stroke-width="9" stroke-linecap="round"/><circle cx="210" cy="105" r="6" fill="#553388"/>`,'An analogue clock'),help:`The long hand points to ${m===0?12:m/5}. ${m===0?`It is ${h} o’clock.`:m===15?`It is quarter past ${h}.`:m===30?`It is half past ${h}.`:`It is quarter to ${h%12+1}.`} The short hand ${m?'is between '+h+' and '+(h%12+1):'points to '+h}.`};}
 else if(type===2){const d=rand(0,6),tomorrow=Math.random()<.5,ans=dayNames[(d+(tomorrow?1:6))%7];q={...q,prompt:`Today is ${dayNames[d]}. What day ${tomorrow?'is tomorrow':'was yesterday'}?`,answer:ans,choices:options(ans,mix(dayNames.filter(n=>n!==ans)).slice(0,3)),html:`<div class="calendar-strip">${dayNames.map((n,i)=>`<span class="${i===d?'today':''}">${n.slice(0,3)}</span>`).join('')}</div>`,help:`${tomorrow?'After':'Before'} ${dayNames[d]} comes ${ans}. The week repeats after Sunday.`};}
 else{const months=['January','February','March','April','May','June','July','August','September','October','November','December'],d=rand(0,11),type=rand(0,2),after=Math.random()<.5,ans=type===2?months[d]:months[(d+(after?1:11))%12];q={...q,prompt:type===2?`Which month is number ${d+1} in the year?`:`Which month comes ${after?'after':'before'} ${months[d]}?`,answer:ans,choices:options(ans,mix(months.filter(n=>n!==ans)).slice(0,3)),html:`<div class="calendar-strip" style="flex-wrap:wrap">${months.map((n,i)=>`<span class="${i===d?'today':''}">${i+1}. ${n}</span>`).join('')}</div>`,help:type===2?`${ans} is month number ${d+1}.`:`${ans} comes ${after?'after':'before'} ${months[d]}. After December, a new year starts with January.`};}
 }

 if(id==='money'){const values=hard?[5,10,20,50,100,200]:[5,10,20,50],coins=[pick(values),pick(values)],sum=coins.reduce((a,b)=>a+b,0);q={...q,prompt:'How much can you spend with these coins?',answer:sum+'c',choices:nums(sum,500).map(n=>n+'c'),html:`<div class="coin-row">${coins.map(n=>`<span class="practice-coin ${n>=100?'gold':''}">${n>=100?'$'+n/100:n+'c'}</span>`).join('')}</div><p>Pretend Australian coins · values shown, sizes simplified</p><div class="shop-tag">My little shop</div>`,help:`${coins.join(' cents plus ')} cents makes ${sum} cents${sum>=100?`. 100 cents is one dollar`:''}.`};}
 if(id==='fractions'){if(Math.random()<.5){const parts=pick([2,4]);q={...q,prompt:'What is the name of the coloured part?',answer:parts===2?'One half':'One quarter',choices:['One half','One quarter','One whole'],html:`<div class="fraction-pie" style="background:conic-gradient(#8c68d5 0 ${360/parts}deg,#f3dfb6 ${360/parts}deg 360deg)">${parts===4?'<i></i>':''}</div>`,help:`The whole is split into ${parts} equal parts. One part is ${parts===2?'a half':'a quarter'}.`}}
 else{const children=pick([2,3,4]),each=rand(1,4),total=children*each;q={...q,prompt:`Share ${total} apples equally among ${children} friends. How many each?`,answer:each,choices:nums(each,20),html:blocks(total,'#dc6c80')+`<p>${children} friends need equal shares.</p>`,help:`Give one apple to each friend, then repeat. ${children} groups of ${each} make ${total}.`}}}
 if(id==='graphs'){const vals=mix([rand(1,2),rand(3,4),rand(5,6)]),names=['Apples','Bananas','Pears'],most=Math.random()<.5,ans=most?names[vals.indexOf(Math.max(...vals))]:vals[0];q={...q,prompt:most?'Which fruit has the most votes?':'How many votes did apples get?',answer:ans,choices:[],html:''};q.choices=most?mix(names):nums(ans,10);q.html=`<div class="picture-graph"><p>Each block = 1 vote</p>${names.map((n,i)=>`<div><strong>${n}</strong>${blocks(vals[i],['#db6c87','#dbb943','#69ab80'][i])}</div>`).join('')}</div>`;q.help=most?`${ans} has the longest row: ${Math.max(...vals)} votes.`:`Count the blocks on the apples row. There are ${ans}.`;}
 if(id==='problems'){const a=rand(2,hard?15:8),b=rand(1,a),add=Math.random()<.5,answer=add?a+b:a-b,name=pick(['Mia','Sam','Ava','Leo','Zoe','Noah','Isla','Aria','Max','Ella','Kai','Ruby','Amir','Lily','Ben','Ivy']),item=pick(['apples','bananas','pears','oranges','plums','mangoes','strawberries','grapes','cherries','peaches','blocks','shells','crayons','stickers','toy cars','flowers']),place=pick(['in a basket','in a box','on a tray','in a bag']),prompt=add?pick([`${name} has ${a} ${item} ${place}. A friend gives ${name} ${b} more. How many now?`,`${name} puts ${a} ${item} ${place}, then adds ${b} more. How many are there altogether?`]):pick([`${name} has ${a} ${item} ${place}. ${name} gives ${b} to a friend. How many are left?`,`${name} has ${a} ${item} ${place}. ${name} takes ${b} out. How many remain?`]);q={...q,prompt,answer,choices:nums(answer,40),html:`<div id="storyMathObjects">${blocks(a,'#dd6c83')}</div><p>Each block stands for one of the ${item}.</p><button class="button" id="actStory">Act it out</button>`,help:add?`Start with ${a}. Add ${b}. There are ${answer} ${item} altogether.`:`Start with ${a}. Take away ${b}. There are ${answer} ${item} left.`,act:{a,b,add,item}};}

 if(id==='money'&&Math.random()<.65){const coinLabel=n=>n>=100?'$'+n/100:n+'c',task=Math.random()<.35;
  if(task){const n=pick([5,10,20,50,100,200]);q={id,prompt:'What is the value of this coin?',answer:coinLabel(n),choices:options(coinLabel(n),mix([5,10,20,50,100,200].filter(v=>v!==n)).slice(0,3).map(coinLabel)),html:`<div class="coin-row"><span class="practice-coin ${n>=100?'gold':''}">${coinLabel(n)}</span></div><p>Pretend Australian coin · read its value</p>`,help:`This coin is worth ${n>=100?n/100+' dollar'+(n===100?'':'s'):n+' cents'}.`}}
  else{const pairs=[[5,5],[10,5],[20,5],[20,10],[20,20],[50,5],[50,10],[50,20],[100,20],[100,50],[200,50]],chosen=pick(hard?pairs:pairs.slice(0,8)),cost=chosen[0]+chosen[1],name=pick(['ball','pencil','apple','book']),answer=chosen.map(coinLabel).join(' + ');q={id,prompt:`The ${name} costs ${cost}c. Which coins pay exactly?`,answer,choices:options(answer,mix(pairs.filter(p=>p[0]+p[1]!==cost)).slice(0,3).map(p=>p.map(coinLabel).join(' + '))),html:pictureClue(name)+`<div class="shop-tag">${name} · ${cost}c</div>`,help:`${chosen[0]} cents plus ${chosen[1]} cents is ${cost} cents. That is the exact price.`}}
 }
 if(id==='measure'&&Math.random()<.25){const count=rand(3,8);q={id,prompt:'How many blocks long is the ribbon?',answer:count,choices:nums(count,12),html:svg(`<rect x="35" y="35" width="${count*40}" height="38" rx="8" fill="#e485a4"/>${Array.from({length:count},(_,i)=>`<rect x="${35+i*40}" y="83" width="40" height="40" fill="#b9a2e5" stroke="white" stroke-width="2"/>`).join('')}`,'A ribbon lined up with equal measuring blocks'),help:`Count the equal blocks from one end to the other, with no gaps. The ribbon is ${count} blocks long.`}}
 if(id==='strategies'){const type=pick(['double','count','five']);if(type==='double'){const n=rand(1,hard?10:5);q={id,prompt:`Double ${n}. How many altogether?`,answer:n*2,choices:nums(n*2,30),html:blocks(n)+blocks(n,'#6ab394'),help:`Double means two equal groups. ${n} plus ${n} is ${n*2}.`}}
 else if(type==='five'){const a=rand(1,4);q={id,prompt:`Make five: ${a} + ? = 5`,answer:5-a,choices:nums(5-a,10),html:`<div class="five-frame">${Array.from({length:5},(_,i)=>`<span class="${i<a?'filled':''}"></span>`).join('')}</div>`,help:`There are ${a} filled spaces. Count the ${5-a} empty spaces to make five.`}}
 else{const a=rand(3,hard?15:7),b=rand(1,3);q={id,prompt:`Keep ${a} in your head. Count on ${b}. Where do you land?`,answer:a+b,choices:nums(a+b,30),html:`<div class="number-hops"><span>${a}</span>${Array.from({length:b},()=>'<b>+1 →</b>').join('')}<span>?</span></div>`,help:`Start at ${a}. Say ${Array.from({length:b},(_,i)=>a+i+1).join(', ')}. You land on ${a+b}.`}}}
 if(id==='solids'){const shapes={cube:'<path d="m150 55 65-32 65 32-65 32Z" fill="#c5a7ee"/><path d="M150 55v90l65 38V87Z" fill="#9272c6"/><path d="M215 87v96l65-38V55Z" fill="#684b9d"/>',sphere:'<defs><radialGradient id="sphereShade" cx="30%" cy="25%"><stop stop-color="#ffdae9"/><stop offset="1" stop-color="#b8477a"/></radialGradient></defs><circle cx="210" cy="105" r="75" fill="url(#sphereShade)"/>',cylinder:'<path d="M145 55v105c0 38 130 38 130 0V55" fill="#5fa9bd"/><ellipse cx="210" cy="55" rx="65" ry="26" fill="#c0e4ec"/><path d="M145 160c0 38 130 38 130 0" fill="none" stroke="#35677c" stroke-width="3"/>',cone:'<path d="M135 166 210 25 285 166Z" fill="#e7ab51"/><ellipse cx="210" cy="166" rx="75" ry="25" fill="#f3d28c"/>',pyramid:'<path d="M130 165 210 25 215 188Z" fill="#6cb09a"/><path d="M210 25 300 160 215 188Z" fill="#3f7e6a"/>'};const name=pick(Object.keys(shapes)),hints={cube:'A cube has six flat square faces, like a dice.',sphere:'A sphere is round all over, like a ball.',cylinder:'A cylinder has two flat circular ends and a curved side, like a tin.',cone:'A cone has a circular base and a point, like a party hat.',pyramid:'A pyramid has triangular sides that meet at a point.'};q={id,prompt:'What is this solid shape called?',answer:name,choices:options(name,mix(Object.keys(shapes).filter(n=>n!==name)).slice(0,3)),html:svg(shapes[name],'A solid shape to name'),help:hints[name]}}
 if(id==='sight'){const groups=[['the','then','them','this'],['was','saw','is','as'],['you','your','yes','yet'],['said','and','can','had'],['we','me','he','be'],['to','go','no','so'],['my','by','I','a']];const words=pick(groups),answer=pick(words);q={id,prompt:'Tap “Hear it”, then find the word.',speech:answer,answer,choices:mix(words),html:'<p>Listen carefully. Look at every letter.</p>',help:`The word is ${answer}. Its letters are ${answer.split('').join(' · ')}.`}}
 return q;
 }
 function fresh(id){let q;for(let n=0;n<20;n++){q=make(id);const key=JSON.stringify([q.prompt,q.answer,q.html]);if(key!==lastBySkill[id]){lastBySkill[id]=key;return q}}return q}
 function scrollActivity(){$('#workspace').scrollIntoView({block:'start',behavior:'auto'})}
 function start(id){cancelAdvance();clearTimeout(timer);stopVoice();if(id==='symmetry'){mirror();scrollActivity();return}if(id==='author'){journal();scrollActivity();return}current=fresh(id);answeredNow=false;retry=false;showQuestion();scrollActivity()}
 function showQuestion(){const q=current,id=q.id;
 $('#workspace').innerHTML=`<div class="explore-shell">${header(meta(id)[1])}<div class="lesson-tools"><button class="button" id="showHow">Show me how</button><button class="button" id="readQuestion">♪ Hear it</button>${id==='levels'?`<label>Reading step <select id="readingStep">${['1 · Short vowels','2 · sh and ch','3 · ee and oa','4 · ai, ay, oy and ou'].map((n,i)=>`<option value="${i}" ${saved.level===i?'selected':''}>${n}</option>`).join('')}</select></label>`:''}${id==='skip'?`<label><input type="checkbox" id="bigHops" ${saved.large?'checked':''}> Challenge up to 1,000</label>`:''}</div><div id="lessonHelp" hidden></div><div class="learning-question"><h3>${q.prompt}</h3>${q.html||''}${q.blend?'<button class="button" id="blendHear">Hear the blended word</button>':''}${id==='sentence'?'<div id="sentenceSlots" class="sentence-slots" aria-label="Your sentence"></div><div id="sentenceTiles" class="sentence-tiles"></div><button class="button" id="resetSentence">Start sentence again</button><button class="button primary" id="checkSentence">Check my sentence</button>':`<div class="answer-list">${q.choices.map((c,i)=>`<button class="button answer" data-answer="${i}">${esc(c)}</button>`).join('')}</div>`}</div><div class="feedback" id="feedback" role="status">Take your time. Have a go!</div><button class="button" id="anotherQuestion">${dailyMode?'Try a different question':'Another question'}</button></div>`;
 bindHome();bindWordHelp();$('#readQuestion').textContent='♪ Read question';$('#readQuestion').onclick=()=>speak((q.speech||q.prompt)+(!['sentence','sight','phonics'].includes(id)?' Your choices are '+q.choices.join(', ')+'.':''));bindQuestionHelp(q);
 $('#anotherQuestion').onclick=()=>start(id);if($('#blendHear'))$('#blendHear').onclick=()=>speak(q.blend);if(reviewRun){$('.pill').textContent='CHECK-IN · '+(reviewRun.step+1)+' OF 5';$('#anotherQuestion').hidden=true;}
 if($('#readingStep'))$('#readingStep').onchange=e=>{saved.level=+e.target.value;persist();start(id)};if($('#bigHops'))$('#bigHops').onchange=e=>{saved.large=e.target.checked;persist();start(id)};
 document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>check(q.choices[+b.dataset.answer]===q.answer,b));
 if(id==='sentence')sentenceGame(q);
 if(q.act)$('#actStory').onclick=()=>{const {a,b,add,item}=q.act;$('#storyMathObjects').innerHTML=blocks(a,'#dd6c83')+(add?'<b>More arrive ↓</b>'+blocks(b,'#69aa85'):`<p>${b} are taken away →</p>`);speak(q.help);if(!add)$('#storyMathObjects').innerHTML=blocks(a-b,'#dd6c83')+`<p>${b} ${item} were taken away.</p>`};
 }
 function bindQuestionHelp(q){
  const button=$('#showHow'),panel=$('#lessonHelp');
  button.setAttribute('aria-expanded','false');
  button.setAttribute('aria-controls','lessonHelp');
  button.onclick=()=>{
   // A detached button must never replay help for an earlier question.
   if(current!==q)return;
   stopVoice();cancelAdvance();
   panel.hidden=!panel.hidden;
   button.setAttribute('aria-expanded',String(!panel.hidden));
   if(panel.hidden)return;
   const guidance=q.id==='sentence'?`${q.help} The sentence is: ${q.sentence}`:q.help;
   panel.innerHTML=`<h3>Let’s work on this question</h3><p class="help-question">${esc(q.prompt)}</p><div class="worked-example">${esc(guidance)}</div><p>Look at your question and have a go.</p>`;
   speak(guidance);
  };
 }

 function sentenceGame(q){const words=q.sentence.split(' '),order=[],tiles=mix(words.map((word,i)=>({word,i})));function paint(){$('#sentenceSlots').innerHTML=order.map(i=>`<button class="button" data-remove="${i}" aria-label="Remove ${esc(words[i])}">${esc(words[i])}</button>`).join('')||'<span>Tap words below to build the sentence</span>';$('#sentenceTiles').innerHTML=tiles.map(t=>`<button class="button" data-tile="${t.i}" ${order.includes(t.i)||answeredNow?'disabled':''}>${esc(t.word)}</button>`).join('');document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{order.push(+b.dataset.tile);paint()});document.querySelectorAll('[data-remove]').forEach(b=>{b.disabled=answeredNow;b.onclick=()=>{order.splice(order.indexOf(+b.dataset.remove),1);paint()}})}paint();$('#resetSentence').onclick=()=>{if(answeredNow)return;order.length=0;paint()};$('#checkSentence').onclick=()=>{if(order.length!==words.length){feedback('Use all the words first.');return}check(order.map(i=>words[i]).join(' ')===q.sentence);paint()}}
 function check(correct,b){if(answeredNow)return;const id=current.id,s=saved.skills[id]||(saved.skills[id]={tries:0,correct:0,completed:0});s.tries++;if(correct){s.correct++;s.completed++;answeredNow=true;star();if(b)b.classList.add('correct');feedback(retry?'You kept trying and worked it out!':'You worked it out!');speak('Well done!');persist();if(dailyMode){today().step++;persist()}if(reviewRun){reviewRun.step++;if(!retry)reviewRun.first++}const next=()=>{cancelAdvance();if(reviewRun){if(reviewRun.step===reviewRun.queue.length){reviewSummary();return}start(reviewRun.queue[reviewRun.step]);return}if(dailyMode){const d=today();if(d.step>=d.queue.length){dailyMode=false;home()}else start(d.queue[d.step])}else start(id)};$('#anotherQuestion').textContent=dailyMode?'Continue adventure':'Next question';$('#anotherQuestion').onclick=next;advanceAfterCorrect(next,dailyMode?'Next adventure':'Next question')}else{retry=true;persist();if(b)b.classList.add('try-again');feedback('Let’s work it out. '+current.help);speak('Have another try. '+current.help)}}
 function progress(){cancelAdvance();$('#workspace').innerHTML=`<div class="explore-shell">${header('A little progress, every day')}<p>For this browser session only. Reading steps are chosen separately from maths challenges.</p><div class="progress-summary"><strong>${stars} effort stars</strong><strong>${Object.values(saved.daily).filter(d=>d.step>=d.queue.length).length} daily adventures finished</strong></div><div class="progress-table"><table><thead><tr><th>Skill</th><th>Completed</th><th>Correct / attempts</th><th>Next step</th></tr></thead><tbody>${skills.map(([id,title])=>{const s=saved.skills[id]||{tries:0,correct:0,completed:0};return `<tr><td>${title}</td><td>${s.completed}</td><td>${s.correct} / ${s.tries}</td><td>${!s.tries?'Explore together':s.correct/s.tries<.75?'Revisit with Show me how':skillLevel(id)?'Ready for a stretch':'Keep practising'}</td></tr>`}).join('')}</tbody></table></div><p>Attempts include helpful retries. Drawing completions celebrate effort, not accuracy. This is practice feedback, not an assessment.</p></div>`;bindHome()}
 function reviewSummary(){const run=reviewRun;reviewRun=null;$('#workspace').innerHTML=`<div class="explore-shell">${header('Look at what you practised!')}<div class="daily-banner"><div><h2>Five skills explored</h2><p>You answered ${run.first} of 5 on the first try.</p><p>Every retry was useful practice. Your skill progress has been updated.</p></div></div><p>${run.queue.map(id=>meta(id)[1]).join(' · ')}</p><button class="button primary" id="reviewProgress">See my progress</button></div>`;bindHome();$('#reviewProgress').onclick=progress}
 function journal(){let kind='retell',drafts={};try{const p=JSON.parse(sessionStorage.getItem('spark-journal')||'{}');if(p&&typeof p==='object')drafts=p}catch{}
  function show(){const fields=kind==='retell'?[['title','My book or story'],['first','First…'],['next','Next…'],['last','At the end…']]:[['to','Dear…'],['message','What I would like to tell you…'],['from','From…']];$('#workspace').innerHTML=`<div class="explore-shell">${header('My little journal')}<p>Write a little, or ask a grown-up to type your words. Your draft lasts for this browser session only.</p><div class="lesson-tools"><button class="button ${kind==='retell'?'primary':''}" id="retellMode">Retell a book</button><button class="button ${kind==='letter'?'primary':''}" id="letterMode">Write a letter</button></div><p>${kind==='retell'?'Tell the important parts in order: first, next, and last.':'Write to a friend, family member, or a child in Year 1. What would you like to tell them?'}</p><div class="journal-fields">${fields.map(([id,label])=>`<label for="journal-${id}">${label}</label><textarea id="journal-${id}" rows="${id==='message'?5:2}" maxlength="1500"></textarea>`).join('')}</div><div class="lesson-tools"><button class="button" id="hearJournal">♪ Hear my writing</button><button class="button" id="saveJournal">Save my writing</button><button class="button primary" id="journalDone">I worked on my writing!</button></div><p id="feedback" role="status"></p></div>`;bindHome();fields.forEach(([id])=>{const input=$('#journal-'+id);input.value=typeof drafts[kind]?.[id]==='string'?drafts[kind][id]:'';input.oninput=()=>{drafts[kind]??={};drafts[kind][id]=input.value;try{sessionStorage.setItem('spark-journal',JSON.stringify(drafts));feedback('Draft kept for this session.')}catch{feedback('Use Save my writing to keep this draft.')}}});$('#retellMode').onclick=()=>{kind='retell';show()};$('#letterMode').onclick=()=>{kind='letter';show()};const text=()=>fields.map(([id,label])=>label+' '+$('#journal-'+id).value).join('\n\n');$('#hearJournal').onclick=()=>speak(text());$('#saveJournal').onclick=()=>download(text(),'my-little-writing.txt','text/plain');$('#journalDone').onclick=()=>{if(!fields.some(([id])=>$('#journal-'+id).value.trim().length>1)){feedback('Add a few words first.');return}const s=saved.skills.author||(saved.skills.author={tries:0,correct:0,completed:0});s.completed++;star();persist();$('#journalDone').disabled=true;feedback('Your ideas matter. Lovely writing practice!')}}show();
 }
 function download(data,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function mirror(){cancelAdvance();let lines=[],activeLine=null,colour='#8054d1',mirrorOn=true;$('#workspace').innerHTML=`<div class="explore-shell">${header('Mirror studio')}<p>Draw one side of a butterfly, a face, or your own idea. The dotted line is the mirror.</p><div class="lesson-tools"><label>Ink <input type="color" id="mirrorColour" value="${colour}"></label><label><input id="mirrorEnabled" type="checkbox" checked> Mirror my drawing</label><button class="button" id="mirrorUndo">Undo</button><button class="button" id="mirrorClear">Fresh paper</button><button class="button" id="mirrorSave">Save picture</button></div><canvas id="mirrorCanvas" width="1000" height="600" aria-label="Symmetry drawing canvas"></canvas><button class="button primary" id="mirrorDone">I made a mirror picture!</button><p id="feedback" role="status"></p></div>`;bindHome();const c=$('#mirrorCanvas'),ctx=c.getContext('2d');function paint(){ctx.clearRect(0,0,1000,600);ctx.setLineDash([8,8]);ctx.strokeStyle='#c7badc';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(500,0);ctx.lineTo(500,600);ctx.stroke();ctx.setLineDash([]);for(const l of lines)for(const flip of l.mirror?[false,true]:[false]){ctx.strokeStyle=ctx.fillStyle=l.colour;ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();l.points.forEach(([x,y],i)=>i?ctx.lineTo(flip?1000-x:x,y):ctx.moveTo(flip?1000-x:x,y));ctx.stroke();if(l.points.length===1){const [x,y]=l.points[0];ctx.beginPath();ctx.arc(flip?1000-x:x,y,3,0,Math.PI*2);ctx.fill()}}}const point=e=>{const r=c.getBoundingClientRect();return [(e.clientX-r.left)*1000/r.width,(e.clientY-r.top)*600/r.height]};c.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();c.setPointerCapture(e.pointerId);activeLine={colour,mirror:mirrorOn,points:[point(e)],pointer:e.pointerId};lines.push(activeLine);paint()};c.onpointermove=e=>{if(activeLine&&activeLine.pointer===e.pointerId){activeLine.points.push(point(e));paint()}};c.onpointerup=c.onpointercancel=c.onlostpointercapture=()=>activeLine=null;$('#mirrorColour').oninput=e=>colour=e.target.value;$('#mirrorEnabled').onchange=e=>mirrorOn=e.target.checked;$('#mirrorUndo').onclick=()=>{lines.pop();paint()};$('#mirrorClear').onclick=()=>{lines=[];paint()};$('#mirrorSave').onclick=()=>{const out=document.createElement('canvas');out.width=1000;out.height=600;const x=out.getContext('2d');x.fillStyle='white';x.fillRect(0,0,1000,600);x.drawImage(c,0,0);const a=document.createElement('a');a.download='my-mirror-picture.png';a.href=out.toDataURL();a.click()};$('#mirrorDone').onclick=()=>{if(!lines.length){feedback('Try drawing a picture first.');return}$('#mirrorDone').disabled=true;const s=saved.skills.symmetry||(saved.skills.symmetry={tries:0,correct:0,completed:0});s.completed++;star();persist();feedback('Look at your matching sides! Lovely drawing.')};paint()}
 function printMenu(){window.sparkPrintMenu(header,bindHome)}
 // Expose pure question generation for local validation, without adding external services.
 window.sparkActivities={make,skills:skills.map(s=>s[0])};
})();
