let advanceTimer=null, advanceCountdown=null;
function cancelAdvance(){clearTimeout(advanceTimer);clearInterval(advanceCountdown);advanceTimer=null;advanceCountdown=null}
function advanceAfterCorrect(next,label='Next question'){
 if(advanceTimer!==null)return;
 document.querySelectorAll('.answer').forEach(b=>b.disabled=true);
 const notice=document.createElement('div');notice.className='advance-notice';
 const count=document.createElement('span');let seconds=3;count.textContent=label+' in 3 seconds…';
 const stay=document.createElement('button');stay.className='button';stay.textContent='Stay here';
 stay.onclick=()=>{cancelAdvance();notice.remove()};notice.append(count,stay);$('#feedback').after(notice);
 advanceCountdown=setInterval(()=>{seconds--;count.textContent=label+' in '+seconds+' seconds…'},1000);
 advanceTimer=setTimeout(()=>{cancelAdvance();stopVoice();next()},3000);
}
let readView='stories', storyId=null, storyPage=0, storyQuiz=false, questionIndex=0, mathKind='count', mathRound=0, mathLimit=5, mathSolved=false, writeKind='letters';
const earned=new Set();
const stories=[
{title:'Sam and the Cat',icon:'🐱',level:'First stories',pages:['Sam has a cat.','The cat is on a mat.','Sam pats the cat.','The cat has a nap.'],question:'Where is the cat?',choices:['On a mat','In a bus','In a pond'],answer:0,draw:'Draw Sam and the cat on the mat.'},
{title:'The Red Bus',icon:'🚌',level:'First stories',pages:['I see a red bus.','Mum and I get on.','We sit on the bus.','The bus goes to the park.'],question:'Where does the bus go?',choices:['To the moon','To the park','To bed'],answer:1,draw:'Draw a red bus going to the park.'},
{title:'Pip the Pup',icon:'🐶',level:'First stories',pages:['Pip is a little pup.','Pip has a ball.','I roll the ball.','Pip runs to get it.'],question:'What does Pip get?',choices:['A hat','A book','A ball'],answer:2,draw:'Draw Pip playing with a ball.'},
{title:'A Big Jump',icon:'🐸',level:'First stories',pages:['A frog sits on a log.','The frog sees a bug.','Hop, hop, hop!','The frog jumps in the pond.'],question:'What does the frog sit on?',choices:['A log','A bed','A bus'],answer:0,draw:'Draw a frog next to a pond.'},
{title:'The Little Seed',icon:'🌱',level:'Read together',pages:['I put a seed in a pot.','I give it a little water.','The sun is warm.','A little leaf pops up.','My plant can grow!'],question:'What pops up?',choices:['A fish','A little leaf','A ball'],answer:1,draw:'Draw your very own growing plant.'},
{title:'A Rainy Day',icon:'☔',level:'Read together',pages:['Tap, tap! Rain is on the roof.','I put on my boots.','Dad and I go out.','We jump in a puddle.','Splash! We have fun.'],question:'What does the child put on?',choices:['A crown','A scarf','Boots'],answer:2,draw:'Draw yourself splashing in a puddle.'},
{title:'The Lost Hat',icon:'👒',level:'Read together',pages:['Meg has a red hat.','A gust of wind blows it off.','The hat lands by a tree.','Meg picks up her hat.','She puts it back on.'],question:'Where does the hat land?',choices:['By a tree','In a boat','On the moon'],answer:0,draw:'Draw Meg and her red hat.'},
{title:'A Picnic for Two',icon:'🧺',level:'Read together',pages:['Ben and Mum pack a bag.','They sit under a big tree.','Ben has an apple.','Mum has a sandwich.','They wave to a little bird.'],question:'What does Ben eat?',choices:['A sandwich','An apple','An egg'],answer:1,draw:'Draw what you would take on a picnic.'}
];
stories.push(
 {title:'Mia Finds a Shell',icon:'🐚',level:'First stories',pages:['Mia walks by the sea.','She sees a tiny shell.','The shell is pink and smooth.','Mia puts it in her pocket.'],question:'What colour is the shell?',choices:['Pink','Green','Blue'],answer:0,draw:'Draw Mia finding a shell.'},
 {title:'The Sleepy Bear',icon:'🐻',level:'First stories',pages:['A bear yawns in the sun.','He finds a soft cave.','He curls up on the leaves.','Good night, little bear.'],question:'Where does the bear sleep?',choices:['In a cave','On a bus','In a tree'],answer:0,draw:'Draw a cosy bear cave.'},
 {title:'Nina’s New Boots',icon:'🥾',level:'First stories',pages:['Nina has new yellow boots.','She puts them on.','Rain makes a big puddle.','Nina jumps with a splash!'],question:'What colour are Nina’s boots?',choices:['Yellow','Purple','Red'],answer:0,draw:'Draw Nina jumping in a puddle.'},
 {title:'The Tiny Ant',icon:'🐜',level:'First stories',pages:['A tiny ant finds a crumb.','The crumb is big and round.','The ant calls three friends.','Together they take it home.'],question:'Who helps the ant?',choices:['Three friends','A fish','A bird'],answer:0,draw:'Draw the tiny ant and friends.'},
 {title:'Ollie’s Kite',icon:'🪁',level:'Read together',pages:['Ollie has a bright kite.','The wind starts to blow.','Up goes the kite!','Ollie runs and laughs.'],question:'What goes up?',choices:['A kite','A shoe','A hat'],answer:0,draw:'Draw a kite in the sky.'},
 {title:'The Busy Bee',icon:'🐝',level:'Read together',pages:['A bee flies to a flower.','It finds yellow pollen.','The bee buzzes home.','The hive is busy.'],question:'Where does the bee go?',choices:['To a flower','To a bed','To a pond'],answer:0,draw:'Draw a bee visiting a flower.'},
 {title:'A Gift for Dad',icon:'🎁',level:'Read together',pages:['Luca makes a card.','He draws a big red heart.','He wraps it in blue paper.','Dad gives Luca a hug.'],question:'What does Luca draw?',choices:['A red heart','A green frog','A yellow star'],answer:0,draw:'Draw a gift and a big heart.'},
 {title:'The Wiggly Worm',icon:'🪱',level:'Read together',pages:['A worm wiggles in the soil.','It sees a little seed.','Rain fills the soil with drops.','The worm makes a safe tunnel.'],question:'Where does the worm wiggle?',choices:['In the soil','On the moon','In a cup'],answer:0,draw:'Draw a worm in the garden.'},
 {title:'Sofia Bakes Bread',icon:'🍞',level:'Read together',pages:['Sofia mixes flour and water.','She kneads the soft dough.','The bread goes in the oven.','It smells warm and nice.'],question:'Where does the bread go?',choices:['In the oven','In a pond','In a shoe'],answer:0,draw:'Draw a warm loaf of bread.'},
 {title:'The Blue Boat',icon:'⛵',level:'Read together',pages:['A blue boat floats on the lake.','A duck swims beside it.','The sun shines on the water.','The boat rocks gently.'],question:'What colour is the boat?',choices:['Blue','Orange','Pink'],answer:0,draw:'Draw a boat on a lake.'}
);
stories.forEach(s=>{s.pages=s.pages.map((text,i)=>({text,visual:[s.icon,'☀️','🌈','⭐','🌿'][i%5]}));s.questions=s.questions||[{question:s.question,choices:s.choices,answer:s.answer},{question:`What happens in ${s.title}?`,choices:['Something kind and fun','A loud storm','Nothing at all'],answer:0},{question:'Would you like to read it again?',choices:['Yes, please!','No words','I cannot tell'],answer:0}]});
function award(key){if(!earned.has(key)){earned.add(key);star()}}
function readTabs(){return `<div class="subnav" aria-label="Reading activities">${[['stories','Little stories'],['sentences','Sentences'],['words','Word play']].map(([k,n])=>`<button class="button ${readView===k?'primary':''}" data-read="${k}" aria-pressed="${readView===k}">${n}</button>`).join('')}</div>`}
function bindReadTabs(){document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{stopVoice();readView=b.dataset.read;render()})}
function stopVoice(){if('speechSynthesis'in window)speechSynthesis.cancel()}
function wordButtons(text){return text.split(' ').map(w=>`<button class="sentence-word" aria-label="Hear ${w.replace(/[.,!?]/g,'')}">${w}</button>`).join(' ')}
function bindWordHelp(){document.querySelectorAll('.sentence-word').forEach(b=>b.onclick=()=>speak(b.textContent.replace(/[.,!?]/g,'')))}
function renderReading(){const root=$('#workspace');if(readView==='words'){renderWordPlay();return}if(storyId===null){root.innerHTML=readTabs()+`<div class="library"><div class="area-head"><div><h2>Pick a little story</h2><p>Start with a first story, or read together with a grown-up.</p></div></div><div class="story-grid">${stories.map((s,i)=>`<button class="story-cover" data-story="${i}"><span class="story-icon" aria-hidden="true">${s.icon}</span><span class="mini-label">${s.level}</span><strong>${s.title}</strong><span>${s.pages.length} little pages ${earned.has('story'+i)?'· ✦ Read':''}</span></button>`).join('')}</div></div>`;bindReadTabs();document.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>{storyId=+b.dataset.story;storyPage=0;storyQuiz=false;render()});return}
const s=stories[storyId], page=s.pages[storyPage], q=s.questions[questionIndex];root.innerHTML=readTabs()+`<div class="studio reading"><aside class="sidebar"><button class="button" id="library">All stories</button><div class="story-icon" aria-hidden="true">${s.icon}</div><h2>${s.title}</h2><p>${s.level}</p><p>${storyQuiz?'Question '+(questionIndex+1)+' of '+s.questions.length:`Page ${storyPage+1} of ${s.pages.length}`}</p><div class="page-dots" aria-label="Story progress">${s.pages.map((_,i)=>`<span class="${i<=storyPage?'filled':''}"></span>`).join('')}</div></aside><div class="canvas-area"><div class="area-head"><h2>${storyQuiz?'Let’s talk about it':'Read a little, imagine a lot.'}</h2><button class="button" id="hear">♪ ${storyQuiz?'Hear question':'Hear page'}</button></div>${storyQuiz?`<div class="question-card"><h3>${q.question}</h3><div class="answer-list">${q.choices.map((c,i)=>`<button class="button answer" data-choice="${i}">${c}</button>`).join('')}</div></div><div class="toolbar"><button class="button" id="reread">Read again</button><button class="button primary" id="drawStory">Draw this story</button></div>`:`<div class="sentence-card story-page"><div class="story-visual" aria-label="Picture for this page">${page.visual}</div><div class="sentence-words">${wordButtons(page.text)}</div><p>Tap a word if you need a little help.</p></div><div class="toolbar"><button class="button" id="backPage" ${storyPage===0?'disabled':''}>Previous page</button><button class="button primary" id="nextPage">${storyPage===s.pages.length-1?'I finished! ✦':'Next page'}</button></div>`}<div id="feedback" class="feedback" role="status"></div></div></div>`;bindReadTabs();bindWordHelp();$('#library').onclick=()=>{stopVoice();storyId=null;render()};$('#hear').onclick=()=>speak(storyQuiz?q.question+'. '+q.choices.join('. '):page.text);if(storyQuiz){document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(+b.dataset.choice===q.answer){award('question'+storyId+'-'+questionIndex);b.classList.add('correct');feedback('✦ That’s right! You remembered the story.');speak('That’s right!');advanceAfterCorrect(()=>{if(questionIndex<s.questions.length-1){questionIndex++;render()}else{storyId=(storyId+1)%stories.length;storyPage=0;questionIndex=0;storyQuiz=false;render()}},questionIndex<s.questions.length-1?'Next question':'Next story')}else{feedback('Good try. Think about the story, or read it again.');b.classList.add('try-again')}});$('#reread').onclick=()=>{stopVoice();storyPage=0;questionIndex=0;storyQuiz=false;render()};$('#drawStory').onclick=()=>{prompts.push(s.draw);promptIndex=prompts.length-1;switchMode('draw')}}else{$('#backPage').onclick=()=>{stopVoice();storyPage--;render()};$('#nextPage').onclick=()=>{stopVoice();if(storyPage===s.pages.length-1){award('story'+storyId);questionIndex=0;storyQuiz=true}else storyPage++;render()}}}
let wordRound=0;
const wordGames=[['cat','The ___ can nap.',['cat','sun','bus']],['sun','The ___ is hot.',['dog','sun','hat']],['dog','The ___ can bark.',['pig','bed','dog']],['hat','I put a ___ on my head.',['hat','fish','bus']],['fish','A ___ can swim.',['cat','fish','hen']],['bed','I sleep in my ___.',['bus','sun','bed']]];
function renderWordPlay(){const [answer,sentence,choices]=wordGames[wordRound];$('#workspace').innerHTML=readTabs()+`<div class="library reading"><div class="area-head"><h2>Find the missing word</h2><button class="button" id="hear">♪ Hear sentence</button></div><div class="sentence-card"><h3 class="gap-sentence">${sentence}</h3></div><div class="answer-list">${choices.map(c=>`<button class="button answer" data-word="${c}">${c}</button>`).join('')}</div><div class="feedback" id="feedback" role="status">Which word makes sense?</div><div class="toolbar"><button class="button primary" id="nextWord">Next word game</button></div></div>`;bindReadTabs();$('#hear').onclick=()=>speak(sentence.replace('___','blank'));document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{speak(b.dataset.word);if(b.dataset.word===answer){award('word'+wordRound);b.classList.add('correct');$('.gap-sentence').textContent=sentence.replace('___',answer);feedback('✦ It fits! Read the whole sentence.');advanceAfterCorrect(()=>{wordRound=(wordRound+1)%wordGames.length;render()},'Next word game')}else feedback('Have another go. Which word fits the sentence?')});$('#nextWord').onclick=()=>{stopVoice();wordRound=(wordRound+1)%wordGames.length;render()}}
const mathTypes=[['count','Count'],['add','Add'],['subtract','Take away'],['compare','More or less'],['shapes','Shapes'],['patterns','Patterns'],['trace','Write numbers']];
function makeMathQuestion(kind,round,limit){const a=round%limit+1,b=(round*3+1)%limit+1;if(kind==='count')return{prompt:'How many dots can you count?',answer:a,choices:numberChoices(a,limit),groups:[a],hint:'Tap each dot once. Say the numbers as you go.'};if(kind==='add'){const left=round%limit,right=(round*2+1)%(limit-left+1),total=left+right;return{prompt:`${left} + ${right} = ?`,spoken:`${left} plus ${right}. How many altogether?`,answer:total,choices:numberChoices(total,limit),groups:[left,right],hint:'Count both groups together.'}}if(kind==='subtract'){const take=round%(a+1);return{prompt:`${a} − ${take} = ?`,spoken:`${a} take away ${take}. How many are left?`,answer:a-take,choices:numberChoices(a-take,limit),groups:[a],removed:take,hint:'The crossed-out dots are taken away. Count the dots left.'}}if(kind==='compare'){return{prompt:'Which group has more?',answer:a===b?'The same':a>b?'Left':'Right',choices:['Left','The same','Right'],groups:[a,b],hint:'Count the left group, then the right. Are they the same?'}}if(kind==='shapes'){const names=['circle','square','triangle','rectangle'];const name=names[round%4];return{prompt:'What is this shape?',answer:name,choices:names,shape:name,hint:{circle:'It is round, with no corners.',square:'It has four equal sides.',triangle:'It has three sides.',rectangle:'It has four corners and two longer sides.'}[name]}}const pats=[['●','▲'],['■','●'],['▲','■']];const pair=pats[round%3],seq=round%2?[pair[0],pair[0],pair[1],pair[0],pair[0]]:[pair[0],pair[1],pair[0],pair[1],pair[0]];return{prompt:'What comes next?',answer:round%2?pair[1]:pair[1],choices:['●','▲','■'],pattern:seq,hint:'Say the shapes in order. Look for the part that repeats.'}}
function numberChoices(n,limit){const set=new Set([n]);for(let d=1;set.size<3;d++){if(n+d<=limit)set.add(n+d);if(set.size<3&&n-d>=0)set.add(n-d)}return [...set].sort((a,b)=>a-b)}
function dots(n,removed=0){return `<div class="dot-group">${n?Array.from({length:n},(_,i)=>`<button class="counter ${i>=n-removed?'removed':''}" ${i>=n-removed?'disabled':''} aria-label="${i>=n-removed?'Taken away':'Count dot '+(i+1)}">${i>=n-removed?'×':''}</button>`).join(''):'<span class="zero-group">0</span>'}</div>`}
function renderMath(){if(mathKind==='trace'){mathKind='count';writeKind='numbers';writeStrokes=[];celebrated=false;letter='0';switchMode('write');return}mathSolved=false;const q=makeMathQuestion(mathKind,mathRound,mathLimit);$('#workspace').innerHTML=`<div class="studio maths"><aside class="sidebar"><div class="mini-label">LITTLE NUMBER ADVENTURES</div><h2>Let's try maths</h2><div class="math-menu">${mathTypes.map(([k,n])=>`<button class="button ${mathKind===k?'primary':''}" data-math="${k}" aria-pressed="${mathKind===k}">${n}</button>`).join('')}</div>${!['shapes','patterns'].includes(mathKind)?`<label class="width-label" for="mathLevel">Our numbers</label><select id="mathLevel"><option value="5" ${mathLimit===5?'selected':''}>Up to 5</option><option value="10" ${mathLimit===10?'selected':''}>Up to 10</option></select>`:''}</aside><div class="canvas-area"><div class="area-head"><h2>${q.prompt}</h2><button class="button" id="hear">♪ Hear question</button></div><div class="math-stage ${mathKind==='compare'?'compare-stage':''}">${q.groups?q.groups.map((n,i)=>`<div class="${mathKind==='compare'?'compare-group':''}" ${mathKind==='compare'?`role="group" aria-label="${i?'Right':'Left'} group"`:''}>${mathKind==='compare'?`<strong>${i?'Right':'Left'}</strong>`:''}${dots(n,q.removed||0)}</div>`).join(mathKind==='add'?'<span class="math-symbol">+</span>':''):''}${q.shape?`<span class="shape shape-${q.shape}" aria-label="Shape to name"></span>`:''}${q.pattern?`<div class="pattern">${q.pattern.join(' ')} <span>?</span></div>`:''}</div><div class="answer-list">${q.choices.map(c=>`<button class="button answer" data-value="${c}">${c}</button>`).join('')}</div><div class="feedback" id="feedback" role="status">Have a go. You can try as many times as you like.</div><div class="toolbar"><button class="button" id="hint">A little hint</button><button class="button primary" id="nextMath">Next question</button></div></div></div>`;document.querySelectorAll('[data-math]').forEach(b=>b.onclick=()=>{mathKind=b.dataset.math;mathRound=0;stopVoice();render()});if($('#mathLevel'))$('#mathLevel').onchange=e=>{mathLimit=+e.target.value;mathRound=0;render()};$('#hear').onclick=()=>speak(q.spoken||q.prompt);$('#hint').onclick=()=>{feedback(q.hint);speak(q.hint)};let counted=0;document.querySelectorAll('.counter:not(.removed)').forEach(b=>b.onclick=()=>{if(b.classList.contains('counted'))return;counted++;b.classList.add('counted');b.textContent=counted;speak(String(counted))});document.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{if(mathSolved)return;if(b.dataset.value===String(q.answer)){mathSolved=true;award(`math-${mathKind}-${mathLimit}-${mathRound}`);b.classList.add('correct');feedback('✦ You worked it out! Well done.');speak('Well done!');advanceAfterCorrect(()=>{mathRound++;render()})}else{b.classList.add('try-again');feedback('Good try! '+q.hint);speak('Have another go. '+q.hint)}});$('#nextMath').onclick=()=>{stopVoice();mathRound++;render()}}
