(() => {
 const topics=[['writing','Trace & write','Letters, words and your name'],['sounds','Sounds & rhymes','Beginning sounds and word families'],['sentences','Sentence builders','Read, order and write'],['stories','Little stories','Read a story and answer four questions'],['count','Counting & numbers','Count, compare and order'],['sums','Add & take away','Fresh addition and subtraction'],['bonds','Number bonds','Find the missing part'],['place','Place value','Hundreds, tens and ones'],['skip','Number patterns','Count in 2s, 5s and 10s'],['shapes','Shape detectives','Draw and describe 2D shapes'],['time','Tell the time','Read clock faces'],['money','Coin counting','Australian coin values'],['fractions','Equal parts','Halves and quarters'],['draw','Imagine & draw','Pictures, labels and storytelling'],['mirror','Mirror pictures','Complete a matching picture']];
 const stories=[
 ['The red ball','Sam has a red ball. He rolls it to Ben. Ben rolls it back. They play on the grass.',['Who has the ball?','What colour is the ball?','Where do they play?','Draw what Sam and Ben do.'],['Sam','Red','On the grass','A picture of rolling a ball']],
 ['A wet dog','Meg has a dog. The dog runs in the rain. His feet get wet. Meg gets a towel.',['Who has a dog?','Where does the dog run?','What gets wet?','Why does Meg get a towel?'],['Meg','In the rain','His feet','To dry the dog']],
 ['The seed','Kim puts a seed in a pot. She adds water. The pot sits in the sun. A little leaf grows.',['What does Kim put in the pot?','What does she add?','Where does the pot sit?','What grows?'],['A seed','Water','In the sun','A leaf']],
 ['At the beach','Dad and Mia go to the beach. Mia digs a big hole. Dad puts water in it. A small crab walks past.',['Who goes with Mia?','What does Mia dig?','What does Dad add?','Which animal walks past?'],['Dad','A big hole','Water','A crab']],
 ['A bird nest','A bird picks up a twig. It puts the twig in a tree. The bird makes a nest. Three eggs sit in the nest.',['What does the bird pick up?','Where is the nest?','How many eggs are there?','Draw the nest.'],['A twig','In a tree','Three','A nest with three eggs']],
 ['Lunch time','Tom has a box. In it are an apple and a bun. Tom sits with May. They eat lunch in the shade.',['What does Tom have?','Name one food in the box.','Who sits with Tom?','Where do they eat?'],['A box','An apple or a bun','May','In the shade']],
 ['The lost hat','Zac cannot find his hat. He looks on his bed. He looks in his bag. The hat is under his chair!',['What is lost?','Where does Zac look first?','Where is the hat?','Draw another place Zac could look.'],['His hat','On his bed','Under his chair','Any sensible place']],
 ['A kind friend','Lily drops her crayons. Max helps pick them up. Lily gives Max some paper. They draw a big rainbow.',['What does Lily drop?','Who helps Lily?','What does Lily give Max?','How is Max kind?'],['Her crayons','Max','Some paper','He helps pick up the crayons']]
 ];
 const words=['cat','dog','sun','hat','pig','hen','bed','bus','cup','map','net','bat'];
 const sentences=['The cat is on the mat.','I can see a red bus.','The dog can run fast.','We can hop and clap.','A little bird is in the tree.','I put my hat in my bag.','The sun is up today.','Mum and I plant a seed.','My fish can swim.','I like to play with my friend.','The pig is in the mud.','We sit on the grass.'];
 const pick=a=>a[Math.floor(Math.random()*a.length)],int=(a,b)=>a+Math.floor(Math.random()*(b-a+1)),shuffle=a=>a.slice().sort(()=>Math.random()-.5);
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const lines=(n=1)=>'<div class="ws-lines">'+Array(n).fill('<div></div>').join('')+'</div>';
 const box=(mirror=false)=>`<div class="ws-draw ${mirror?'ws-mirror':''}">${mirror?'<svg viewBox="0 0 400 140" aria-label="Half a butterfly to reflect"><path d="M200 70 C100 -20 65 45 170 75 C80 75 105 155 200 90" fill="none" stroke="black" stroke-width="2"/></svg>':''}</div>`;
 const clock=(h,m=0)=>`<svg class="ws-clock" viewBox="0 0 120 120" aria-label="Clock"><circle cx="60" cy="60" r="54" fill="white" stroke="black" stroke-width="2"/>${Array.from({length:12},(_,i)=>{const a=(i+1)*Math.PI/6;return `<text x="${60+43*Math.sin(a)}" y="${64-43*Math.cos(a)}" text-anchor="middle" font-size="11">${i+1}</text>`}).join('')}<path d="M60 60 L${60+36*Math.sin(m*Math.PI/30)} ${60-36*Math.cos(m*Math.PI/30)} M60 60 L${60+25*Math.sin((h+m/60)*Math.PI/6)} ${60-25*Math.cos((h+m/60)*Math.PI/6)}" stroke="black" stroke-width="3"/></svg>`;
 function generate(kind,limit,letter,index=0){let tasks=[],answers=[];const add=(html,answer)=>{tasks.push(html);answers.push(answer)};
 if(kind==='writing'){const samples=[letter,letter,letter];for(const word of samples)add(`<p>Trace ${esc(word)}, then write it by yourself.</p><div class="ws-trace">${Array(word.length>5?2:4).fill(esc(word)).join(' &nbsp; ')}</div>${lines(1)}`,'Practise comfortable letter formation.');add('<p>Write your name and draw something that starts with its first sound.</p>'+lines()+box(),'Open-ended');}
 if(kind==='sounds'){for(const word of shuffle(words).slice(0,4))add(`<p>Read <b>${word}</b>. Say its sounds. Write the first sound: ____</p><p>Write the word: ____________________</p>`,word[0]);add('<p>Circle the words that rhyme with cat: &nbsp; hat &nbsp; dog &nbsp; bat &nbsp; sun</p>','hat, bat');add('<p>Add a sound to make three words: &nbsp; __at &nbsp; __an &nbsp; __en</p>','Examples: cat, fan, hen');}
 if(kind==='sentences'){for(const sentence of shuffle(sentences).slice(0,3))add(`<p>Read: <b>${sentence}</b></p><p>Put these words in order: ${shuffle(sentence.split(' ')).join(' / ')}</p>${lines()}`,sentence);add('<p>Write your own sentence. Start with a capital letter and end with a full stop.</p>'+lines()+'<p>Draw your sentence.</p>'+box(),'Open-ended');}
 if(kind==='stories'){const s=stories[index%stories.length];add(`<h3>${s[0]}</h3><p class="ws-story">${s[1]}</p>`,'Read together if needed.');s[2].forEach((q,i)=>add(`<p>${i+1}. ${q}</p>${q.startsWith('Draw')?box():lines()}`,s[3][i]));}
 if(kind==='count'){for(let i=0;i<2;i++){const n=int(2,Math.min(limit,20));add('<p>Count the dots and write the number: ____</p><div class="ws-dots">'+Array(n).fill('<i></i>').join('')+'</div>',n)}for(let i=0;i<2;i++){const a=int(0,limit),b=int(0,limit);add(`<p>Write &lt;, &gt; or = : &nbsp; ${a} ____ ${b}</p>`,a===b?'=':a>b?'>':'<')}const ns=Array.from({length:4},()=>int(0,limit));add(`<p>Put these numbers in order, smallest first: ${ns.join(', ')}</p>${lines()}`,ns.slice().sort((a,b)=>a-b).join(', '));add(`<p>Write the number after ${limit-1}: ____</p>`,limit);}
 if(['sums','bonds'].includes(kind)){for(let i=0;i<8;i++){const total=int(2,limit),a=int(0,total),b=total-a,sub=i%2;add(`<p class="ws-sum">${kind==='bonds'?`${a} + ____ = ${total}`:sub?`${total} − ${a} = ____`:`${a} + ${b} = ____`}</p>`,kind==='bonds'||sub?b:total)}}
 if(kind==='place'){for(let i=0;i<6;i++){const n=int(0,Math.min(limit,999));add(`<p><b>${n}</b> = ____ hundreds + ____ tens + ____ ones</p><p>Expanded form: ______________________________</p>`,`${Math.floor(n/100)} hundreds, ${Math.floor(n/10)%10} tens, ${n%10} ones; ${Math.floor(n/100)*100} + ${Math.floor(n/10)%10*10} + ${n%10}`)}}
 if(kind==='skip'){for(let i=0;i<6;i++){const step=pick([2,5,10].filter(n=>n*3<=limit)),start=int(0,Math.floor((limit-3*step)/step))*step;add(`<p>Count in ${step}s: ${start}, ${start+step}, ____, ____</p>`,`${start+step*2}, ${start+step*3}`)}}
 if(kind==='shapes'){for(const [name,sides] of shuffle([['triangle',3],['square',4],['rectangle',4],['pentagon',5],['hexagon',6],['octagon',8]]).slice(0,3))add(`<p>Draw a ${name}. How many straight sides? ____</p>${box()}`,sides);add('<p>Find a round object. Draw it and write its name.</p>'+lines(),'Open-ended');}
 if(kind==='time'){for(const h of shuffle(Array.from({length:12},(_,i)=>i+1)).slice(0,6)){const m=pick([0,15,30,45]);add(`${clock(h,m)}<p>Write the time: ____ : ____</p>`,`${h}:${String(m).padStart(2,'0')}`)}}
 if(kind==='money'){for(let i=0;i<6;i++){const coins=Array.from({length:int(2,4)},()=>pick([5,10,20,50]));add(`<p>Add these Australian coin values:</p><div class="ws-coins">${coins.map(n=>`<span>${n}c</span>`).join('')}</div><p>Total: ____ cents</p>`,coins.reduce((a,b)=>a+b,0)+' cents')}}
 if(kind==='fractions'){for(const parts of [2,4,2,4])add(`<p>Colour one ${parts===2?'half':'quarter'} of the bar.</p><div class="ws-fraction">${Array(parts).fill('<span></span>').join('')}</div>`,`Colour 1 of ${parts} equal parts.`);add('<p>Share 8 apples equally between 2 friends. Draw each friend’s share.</p>'+box(),'4 apples each');}
 if(kind==='draw'){for(const prompt of shuffle(['Invent an animal. Give it a name.','Draw a garden. Label three things.','Draw a place where you feel happy.','Design a home for a tiny mouse.','Draw what happens next in your favourite story.','Draw a helpful robot. What can it do?']).slice(0,2))add(`<p>${prompt}</p>${box()}${lines()}`,'Open-ended; invite the child to explain their picture.');}
 if(kind==='mirror'){add('<p>Finish the butterfly. Make the two sides match.</p>'+box(true),'Reflect the left wing on the right.');add('<p>Draw your own matching pattern on both sides of the dotted line.</p><div class="ws-draw ws-mirror"></div>','Matching reflected shapes.');add('<p>Find something with matching halves. Draw it.</p>'+box(),'Examples: butterfly, leaf, heart.');}
 return {kind,title:topics.find(t=>t[0]===kind)[1],tasks,answers};}
 window.sparkWorksheet={topics,generate};
 window.sparkPrintMenu=(header,bindHome)=>{
 document.querySelector('#workspace').innerHTML=`<div class="explore-shell">${header('Printable practice studio')}<p>Build a little practice pack. Pick a topic or mix several skills, then make a fresh version whenever you like.</p><div class="ws-settings"><label>Activity<select id="sheetKind"><option value="mixed">Mixed practice pack</option>${topics.map(([id,title,desc])=>`<option value="${id}">${title} · ${desc}</option>`).join('')}</select></label><label>Pages<select id="sheetPages"><option>1</option><option selected>3</option><option>5</option><option>10</option></select></label><label>Number range<select id="sheetLimit">${[10,20,50,100,1000].map(n=>`<option ${n===20?'selected':''}>${n}</option>`).join('')}</select></label><label>Tracing set<select id="traceSet"><option value="custom">One letter, word or name</option><option value="lower">All lowercase letters a–z (26 pages)</option><option value="upper">All uppercase letters A–Z (26 pages)</option><option value="both">All letters A–Z and a–z (26 pages)</option><option value="digits">All digits 0–9 (10 pages)</option><option value="numbers">Numbers 1–20 (20 pages)</option></select></label><label>Trace a letter, word or name<input id="sheetLetter" value="a" maxlength="12"></label><button class="button primary" id="makeSheet">Make my practice pack</button></div><div id="sheetPreview"></div></div>`;bindHome();
 document.querySelector('#makeSheet').onclick=()=>{const val=id=>document.querySelector(id).value,kind=val('#sheetKind'),count=+val('#sheetPages'),limit=+val('#sheetLimit'),letter=val('#sheetLetter').replace(/[^a-zA-Z0-9 ]/g,'').trim()||'a',pool=shuffle(topics.map(t=>t[0])),storyStart=int(0,stories.length-1);const set=val('#traceSet'),samples=set==='lower'?[...'abcdefghijklmnopqrstuvwxyz']:set==='upper'?[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ']:set==='both'?[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map(c=>c+' '+c.toLowerCase()):set==='digits'?Array.from({length:10},(_,i)=>String(i)):set==='numbers'?Array.from({length:20},(_,i)=>String(i+1)):null;const sheets=samples?samples.map(sample=>generate('writing',limit,sample,0)):Array.from({length:count},(_,i)=>generate(kind==='mixed'?pool[i%pool.length]:kind,limit,letter,storyStart+i));document.querySelector('#sheetPreview').innerHTML=`<div class="print-controls"><button class="button primary" id="printSheet">Print / Save PDF</button><button class="button" id="freshSheet">New questions</button><label><input type="checkbox" id="includeAnswers"> Include answer key</label><p>${sheets.length} practice page${sheets.length===1?'':'s'} · Preview below</p></div><article class="print-sheet">${sheets.map((s,i)=>`<section class="ws-page"><div class="ws-brand">LITTLE SPARKLE · ${i+1} / ${sheets.length}</div><h2>${s.title}</h2><p class="ws-name">Name: ____________________ &nbsp; Date: ____________</p><div class="ws-tasks ${['sums','bonds','time','money'].includes(s.kind)?'ws-columns':''}">${s.tasks.map(t=>`<div class="ws-task">${t}</div>`).join('')}</div><p class="ws-celebrate">I had a go! &nbsp; ☆ ☆ ☆ &nbsp; Colour a star for your effort.</p></section>`).join('')}<section class="sheet-answers" hidden><h2>Grown-up answer key</h2>${sheets.map((s,i)=>`<div class="ws-answer"><h3>Page ${i+1} · ${s.title}</h3><ol>${(s.kind==='stories'?s.answers.slice(1):s.answers).map(a=>`<li>${esc(a)}</li>`).join('')}</ol></div>`).join('')}</section></article>`;document.querySelector('#includeAnswers').onchange=e=>document.querySelector('.sheet-answers').hidden=!e.target.checked;document.querySelector('#printSheet').onclick=()=>window.print();document.querySelector('#freshSheet').onclick=()=>document.querySelector('#makeSheet').click();};
 };
})();
